name: Manual
on:
  workflow_dispatch:                                # 手動実行イベント
    inputs:                                         # 入力パラメータの定義
      greeting:                                     # 入力パラメータ名
        type: string                                # データ型（文字列）
        default: Hello                              # 入力パラメータのデフォルト値
        required: true                              # 入力パラメータの必須フラグ
        description: A cheerful world               # 入力パラメータの概要

jobs:
    run:
        runs-on: ubuntu-latest                      # ランナー（Ubuntuで実行）
        steps:
            - run: echo "${{ inputs.greeting }}"    # 入力パラメータ「greeting」の参照
